DROP TABLE IF EXISTS billing;
DROP TABLE IF EXISTS hiree;

DROP TABLE IF EXISTS usergroup;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organization;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS skill;
DROP TABLE IF EXISTS exam;
DROP TABLE IF EXISTS questions;





