// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Status       string         `json:"status"`
	Type         int32          `json:"type"`
	Userid       uuid.UUID      `json:"userid"`
	Orgid        uuid.UUID      `json:"orgid"`
	City         sql.NullString `json:"city"`
	CreatedAt    time.Time      `json:"created_at"`
	LastModified sql.NullTime   `json:"last_modified"`
}

type Examround struct {
	ID           uuid.UUID    `json:"id"`
	Type         int32        `json:"type"`
	Level        int32        `json:"level"`
	Time         int32        `json:"time"`
	Userid       uuid.UUID    `json:"userid"`
	Orgid        uuid.UUID    `json:"orgid"`
	CreatedAt    time.Time    `json:"created_at"`
	LastModified sql.NullTime `json:"last_modified"`
}

type Org struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	Userid    uuid.UUID     `json:"userid"`
	Accountid uuid.NullUUID `json:"accountid"`
}

type Question struct {
	ID           uuid.UUID     `json:"id"`
	Type         int32         `json:"type"`
	Level        int32         `json:"level"`
	Format       int32         `json:"format"`
	Userid       uuid.UUID     `json:"userid"`
	Orgid        uuid.NullUUID `json:"orgid"`
	Question     string        `json:"question"`
	QuestionTime sql.NullInt32 `json:"question_time"`
	CreatedAt    time.Time     `json:"created_at"`
	LastModified sql.NullTime  `json:"last_modified"`
}

type User struct {
	ID           uuid.UUID     `json:"id"`
	Status       int32         `json:"status"`
	Type         int32         `json:"type"`
	Orgid        uuid.NullUUID `json:"orgid"`
	FirstName    string        `json:"first_name"`
	LastName     string        `json:"last_name"`
	Email        string        `json:"email"`
	Hashedpwd    string        `json:"hashedpwd"`
	CreatedAt    time.Time     `json:"created_at"`
	LastModified sql.NullTime  `json:"last_modified"`
}

type Usersession struct {
	ID           uuid.UUID `json:"id"`
	Userid       uuid.UUID `json:"userid"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	ExpiresAt    time.Time `json:"expires_at"`
	IsBlocked    bool      `json:"is_blocked"`
	CreatedAt    time.Time `json:"created_at"`
}
