// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, uUuid uuid.UUID) error
	GetUser(ctx context.Context, uUuid uuid.UUID) (User, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
